let str=" this is demo string to apply function ";
console.log(str.slice(0,5))
console.log(str.charAt(5))
console.log(str.includes("is"))
console.log(str.endsWith("function"))
console.log(str.length)
console.log(str.match(/[a,e,i,o,u]/gm))
console.log(str.startsWith("this"))
console.log(str.search("demo"))
console.log(str.indexOf("demo"))
console.log(str=str.concat(" this is second string"))
console.log(str.lastIndexOf("is"))
console.log(str.split(" "))
console.log(str.toLowerCase())
console.log(str.toUpperCase())
console.log(str.replace("function","method"))
console.log(str.substring(13))
console.log(str.trim())
console.log(str.padEnd(68,"h"))

